#!/usr/bin/env python3
"""Public endpoint catalog for the local status/dashboard server."""

from __future__ import annotations

PUBLIC_ENDPOINTS = (
    {
        "method": "GET",
        "path": "/health",
        "category": "telemetry",
        "description": "Return receiver liveness and latest local snapshot availability.",
        "response": "JSON health payload",
    },
    {
        "method": "GET",
        "path": "/status",
        "category": "telemetry",
        "description": "Return the latest posted node status snapshot.",
        "response": "JSON status payload",
    },
    {
        "method": "GET",
        "path": "/status_history",
        "category": "telemetry",
        "description": "Return summarized recent status snapshots, optionally filtered by node_id.",
        "response": "JSON history rows",
    },
    {
        "method": "GET",
        "path": "/status_equity_rollups",
        "category": "telemetry",
        "description": "Summarize sanitized status-history equity snapshots by UTC day, month, and year.",
        "response": "JSON status-history performance rollups",
    },
    {
        "method": "GET",
        "path": "/status_equity_rollups_snapshot",
        "category": "telemetry",
        "description": "Return the latest persisted sanitized status-history equity rollup artifact.",
        "response": "JSON persisted rollup snapshot",
    },
    {
        "method": "GET",
        "path": "/status_equity_rollups_export",
        "category": "telemetry",
        "description": "Download sanitized status-history daily, monthly, and yearly equity rollups.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/runtime_sessions",
        "category": "telemetry",
        "description": "Return bounded paper/shadow runtime session-folder evidence from configured data roots.",
        "response": "JSON runtime session summaries",
    },
    {
        "method": "GET",
        "path": "/runtime_session_detail",
        "category": "telemetry",
        "description": "Return bounded public-safe file/category detail for one runtime session folder.",
        "response": "JSON runtime session file detail",
    },
    {
        "method": "GET",
        "path": "/runtime_sessions_export",
        "category": "telemetry",
        "description": "Download bounded paper/shadow runtime session-folder evidence from configured data roots.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/telemetry_run_artifacts",
        "category": "telemetry",
        "description": "Return sanitized account history for one published telemetry run's bridged artifacts.",
        "response": "JSON account artifact summary",
    },
    {
        "method": "GET",
        "path": "/remote_nodes",
        "category": "telemetry",
        "description": "Return sanitized latest read-only monitoring summaries by node.",
        "response": "JSON node summaries",
    },
    {
        "method": "GET",
        "path": "/remote_nodes_export",
        "category": "telemetry",
        "description": "Download sanitized latest read-only monitoring summaries by node.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/remote_node_detail",
        "category": "telemetry",
        "description": "Return bounded sanitized latest status detail and history for one node.",
        "response": "JSON node detail",
    },
    {
        "method": "GET",
        "path": "/remote_node_detail_export",
        "category": "telemetry",
        "description": "Download bounded sanitized status detail, history, runs, alerts, and activity for one node.",
        "response": "CSV download",
    },
    {
        "method": "POST",
        "path": "/status",
        "category": "telemetry",
        "description": "Receive and persist a node status snapshot.",
        "response": "JSON receipt",
    },
    {
        "method": "GET",
        "path": "/data_catalog",
        "category": "data",
        "description": "Inspect CSV/parquet data files under configured public data roots.",
        "response": "JSON catalog with quality metadata",
    },
    {
        "method": "GET",
        "path": "/data_symbol_index",
        "category": "data",
        "description": "Build a broad filename/path-inferred saved-data symbol index without parsing full data files.",
        "response": "JSON symbol/file index",
    },
    {
        "method": "GET",
        "path": "/data_symbol_index_detail",
        "category": "data",
        "description": "List bounded filename/path-inferred candidate files for one saved-data symbol.",
        "response": "JSON symbol candidate file detail",
    },
    {
        "method": "GET",
        "path": "/data_symbol_index_detail_export",
        "category": "data",
        "description": "Download bounded filename/path-inferred candidate files for one saved-data symbol.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_symbol_index_export",
        "category": "data",
        "description": "Download the broad filename/path-inferred saved-data symbol index.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/docs/{name}",
        "category": "help",
        "description": "Serve allowlisted public Markdown docs for in-dashboard runbooks and guidance.",
        "response": "Markdown text",
    },
    {
        "method": "GET",
        "path": "/data_catalog_export",
        "category": "data",
        "description": "Download saved data catalog metadata.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_symbol_directory",
        "category": "data",
        "description": "Return saved-data symbol-level universe summaries.",
        "response": "JSON symbol directory summaries",
    },
    {
        "method": "GET",
        "path": "/data_history_matrix",
        "category": "data",
        "description": "Return saved-data grouped history inventory by asset/source/bar/session.",
        "response": "JSON saved history matrix",
    },
    {
        "method": "GET",
        "path": "/data_history_matrix_export",
        "category": "data",
        "description": "Download saved-data grouped history inventory by asset/source/bar/session.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_symbol_directory_export",
        "category": "data",
        "description": "Download saved-data symbol-level universe summaries.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_catalog_scan_export",
        "category": "data",
        "description": "Download data-root catalog scan diagnostics and skipped-file samples.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_detail",
        "category": "data",
        "description": "Inspect one saved data file with range-filtered sampled or full-in-range price/volume series.",
        "response": "JSON dataset detail and viewer series",
    },
    {
        "method": "GET",
        "path": "/data_missing_intervals_export",
        "category": "data",
        "description": "Download inferred missing expected timestamps for one saved data file.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_coverage",
        "category": "data",
        "description": "Summarize saved-data date coverage by symbol for heatmap-style views.",
        "response": "JSON coverage bins and rows",
    },
    {
        "method": "GET",
        "path": "/data_coverage_export",
        "category": "data",
        "description": "Download saved-data symbol/date coverage rows.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_gap_summary",
        "category": "data",
        "description": "Summarize worst saved-data timestamp gaps and missing calendar days.",
        "response": "JSON aggregate gap rows",
    },
    {
        "method": "GET",
        "path": "/data_gap_summary_export",
        "category": "data",
        "description": "Download worst saved-data timestamp and calendar gap rows.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_minute_heatmap",
        "category": "data",
        "description": "Summarize saved-data intraday interval completeness by UTC hour and worst date/hour.",
        "response": "JSON hourly and date/hour missing-interval heatmap rows",
    },
    {
        "method": "GET",
        "path": "/data_minute_heatmap_export",
        "category": "data",
        "description": "Download saved-data intraday interval completeness rows.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_symbol_diagnostic",
        "category": "data",
        "description": "Explain whether a requested symbol is visible, skipped, unconfigured, or absent.",
        "response": "JSON symbol visibility diagnosis",
    },
    {
        "method": "GET",
        "path": "/data_symbol_diagnostics",
        "category": "data",
        "description": "Run bounded visibility diagnostics for a pasted symbol universe.",
        "response": "JSON batch symbol visibility diagnoses",
    },
    {
        "method": "GET",
        "path": "/data_symbol_diagnostics_export",
        "category": "data",
        "description": "Download bounded visibility diagnostics for a pasted symbol universe.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_detail_export",
        "category": "data",
        "description": "Download the current saved-data detail date range as normalized CSV.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/data_storage_audit",
        "category": "data",
        "description": "Compare local CSV/parquet files on disk with catalog-visible saved-data rows.",
        "response": "JSON root-by-root storage audit",
    },
    {
        "method": "GET",
        "path": "/data_storage_audit_export",
        "category": "data",
        "description": "Download root-by-root saved-data storage audit metadata.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/fetch_manifests",
        "category": "data",
        "description": "List historical-data fetch job manifests.",
        "response": "JSON fetch-job manifest summaries",
    },
    {
        "method": "GET",
        "path": "/fetch_jobs",
        "category": "data",
        "description": "Alias for /fetch_manifests for users looking for fetch jobs.",
        "response": "JSON fetch-job manifest summaries",
    },
    {
        "method": "GET",
        "path": "/fetch_manifest_roots",
        "category": "data",
        "description": "List configured fetch manifest roots and manifest counts.",
        "response": "JSON fetch-manifest root summaries",
    },
    {
        "method": "GET",
        "path": "/fetch_manifests_export",
        "category": "data",
        "description": "Download historical-data fetch job manifest summaries.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/fetch_manifest_detail",
        "category": "data",
        "description": "Inspect one historical-data fetch job manifest.",
        "response": "JSON fetch-job manifest detail",
    },
    {
        "method": "GET",
        "path": "/fetch_manifest_detail_export",
        "category": "data",
        "description": "Download selected fetch manifest symbols, outputs, errors, and retry/pacing events.",
        "response": "CSV download",
    },
    {
        "method": "POST",
        "path": "/data_alignment",
        "category": "data",
        "description": "Preview timestamp alignment for selected saved datasets.",
        "response": "JSON alignment summary",
    },
    {
        "method": "POST",
        "path": "/data_compare",
        "category": "data",
        "description": "Compare normalized close paths for several saved datasets over one local time range.",
        "response": "JSON normalized saved-data comparison series",
    },
    {
        "method": "GET",
        "path": "/config_options",
        "category": "config",
        "description": "Return public config-builder plugin, mode, action, preset, and default options.",
        "response": "JSON options",
    },
    {
        "method": "POST",
        "path": "/config_draft",
        "category": "config",
        "description": "Generate an example public workbench config draft, optionally saving it locally.",
        "response": "JSON draft with YAML and validation",
    },
    {
        "method": "POST",
        "path": "/config_draft_preview",
        "category": "config",
        "description": "Preview and validate a public workbench config draft without saving it.",
        "response": "JSON unsaved draft with YAML and validation",
    },
    {
        "method": "GET",
        "path": "/config_drafts",
        "category": "config",
        "description": "List saved public workbench config drafts.",
        "response": "JSON draft list",
    },
    {
        "method": "GET",
        "path": "/config_drafts_export",
        "category": "config",
        "description": "Download saved public workbench config draft inventory rows.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/config_draft_validations",
        "category": "config",
        "description": "Validate every saved draft against public workbench guardrails.",
        "response": "JSON validation summary",
    },
    {
        "method": "GET",
        "path": "/config_draft_detail",
        "category": "config",
        "description": "Load one valid saved draft with YAML, commands, and alignment summary.",
        "response": "JSON draft detail",
    },
    {
        "method": "GET",
        "path": "/config_draft_yaml",
        "category": "config",
        "description": "Download one validated saved draft YAML file.",
        "response": "YAML download",
    },
    {
        "method": "POST",
        "path": "/config_draft/delete",
        "category": "config",
        "description": "Delete one saved draft YAML after explicit confirmation.",
        "response": "JSON deletion result",
    },
    {
        "method": "POST",
        "path": "/config_draft/run",
        "category": "config",
        "description": "Validate, replay, or simulated-paper-run a saved public draft with bounds.",
        "response": "JSON run record",
    },
    {
        "method": "GET",
        "path": "/config_draft_runs",
        "category": "runs",
        "description": "List recent saved-draft run records.",
        "response": "JSON run list",
    },
    {
        "method": "GET",
        "path": "/config_draft_run_comparison",
        "category": "runs",
        "description": "Return public-safe run comparison metrics and leaders.",
        "response": "JSON comparison",
    },
    {
        "method": "GET",
        "path": "/config_draft_daily_rollups",
        "category": "runs",
        "description": "Summarize archived account artifacts by UTC day for current-performance views.",
        "response": "JSON daily run rollups",
    },
    {
        "method": "GET",
        "path": "/config_draft_runs_export",
        "category": "runs",
        "description": "Download public-safe recent run comparison rows.",
        "response": "CSV download",
    },
    {
        "method": "GET",
        "path": "/config_draft_run_detail",
        "category": "runs",
        "description": "Return command, timing, stdout, and stderr detail for one run.",
        "response": "JSON run detail",
    },
    {
        "method": "GET",
        "path": "/config_draft_run_evidence",
        "category": "runs",
        "description": "Return bounded run log, artifact-file, and execution evidence for one saved-draft run.",
        "response": "JSON run evidence",
    },
    {
        "method": "GET",
        "path": "/config_draft_artifacts",
        "category": "runs",
        "description": "Return sanitized latest artifacts for a saved draft output directory.",
        "response": "JSON artifact summary",
    },
    {
        "method": "GET",
        "path": "/config_draft_run_artifacts",
        "category": "runs",
        "description": "Return sanitized archived artifacts for one saved-draft run.",
        "response": "JSON artifact summary",
    },
    {
        "method": "GET",
        "path": "/config_draft_run_artifacts_export",
        "category": "runs",
        "description": "Download sanitized archived artifacts for one saved-draft run.",
        "response": "JSON download",
    },
    {
        "method": "POST",
        "path": "/order_preview_approval",
        "category": "runs",
        "description": "Write one local approval file for a held order preview after validating its preview digest.",
        "response": "JSON approval result",
    },
    {
        "method": "GET",
        "path": "/workbench_status",
        "category": "workbench",
        "description": "Return local draft, run, archive, and cleanup status.",
        "response": "JSON status summary",
    },
    {
        "method": "GET",
        "path": "/workbench_cleanup_plan",
        "category": "workbench",
        "description": "Preview orphaned workbench archive/output cleanup.",
        "response": "JSON cleanup plan",
    },
    {
        "method": "POST",
        "path": "/workbench_cleanup",
        "category": "workbench",
        "description": "Dry-run or apply orphaned workbench archive/output cleanup.",
        "response": "JSON cleanup result",
    },
    {
        "method": "GET",
        "path": "/workbench_diagnostics",
        "category": "workbench",
        "description": "Probe state directory, data roots, and dashboard asset availability.",
        "response": "JSON diagnostics",
    },
    {
        "method": "GET",
        "path": "/workbench_snapshot_export",
        "category": "workbench",
        "description": "Download a public-safe snapshot of workbench state and metadata.",
        "response": "JSON download",
    },
    {
        "method": "GET",
        "path": "/workbench_endpoints",
        "category": "workbench",
        "description": "Return this public endpoint map.",
        "response": "JSON endpoint list",
    },
    {
        "method": "GET",
        "path": "/commands",
        "category": "remote",
        "description": "List pending local remote-control commands and audit returned pending commands.",
        "response": "JSON command list",
    },
    {
        "method": "POST",
        "path": "/commands",
        "category": "remote",
        "description": "Queue an allow-listed local remote-control command.",
        "response": "JSON command record",
    },
    {
        "method": "POST",
        "path": "/commands/cancel",
        "category": "remote",
        "description": "Cancel a pending local remote-control command.",
        "response": "JSON cancel result",
    },
    {
        "method": "GET",
        "path": "/command_results",
        "category": "remote",
        "description": "List recent command results for a node.",
        "response": "JSON result list",
    },
    {
        "method": "POST",
        "path": "/command_results",
        "category": "remote",
        "description": "Receive and persist a command execution result.",
        "response": "JSON receipt",
    },
    {
        "method": "GET",
        "path": "/command_audit",
        "category": "remote",
        "description": "List sanitized command queue/cancel/result/pending-return audit events.",
        "response": "JSON audit event list",
    },
    {
        "method": "GET",
        "path": "/command_audit_export",
        "category": "remote",
        "description": "Download sanitized command queue/cancel/result/pending-return audit events with integrity metadata.",
        "response": "CSV audit event export",
    },
)
